eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

my:
  secretKey: test123


spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: books-service
          uri: lb://BOOKS-SERVICE
          predicates:
            - Path=/v1/books/**
          filters:
            -  AuthFilter
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/v1/carts/**
          filters:
            - AuthFilter
        - id: orders-service
          uri: lb://ORDERS-SERVICE
          predicates:
            - Path=/v1/orders/**
          filters:
            - AuthFilter
        - id: payments-service
          uri: lb://PAYMENTS-SERVICE
          predicates:
            - Path=/v1/payments/**
          filters:
            - AuthFilter

server:
  port: 8000